server:
  address: 127.0.0.9
  port: 2233
  compression:
    enabled: true
    min-response-size: 1KB
    mime-types:
      - text/*
      - application/javascript
      - text/javascript
      - application/json
      - application/xml
    excluded-user-agents:
      - application/octet-stream
      - application/zip
      - application/x-gzip
      - image/*
      - audio/*
      - video/*
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssm_web
    username: yjl
    password: yjl

  sql:
    init:
      platform: mysql
mybatis:
  config-location:  classpath:mybatis-config.xml
